# Generated by Django 5.2.10 on 2026-01-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Loja')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop/', verbose_name='Logo')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('business_hours', models.TextField(help_text='Ex: Seg-Sex: 8h-20h | Sáb: 8h-18h | Dom: 8h-14h', verbose_name='Horário de Funcionamento')),
                ('about', models.TextField(blank=True, verbose_name='Sobre a Loja')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração da Loja',
                'verbose_name_plural': 'Configuração da Loja',
            },
        ),
    ]
