# Generated by Django 5.2.10 on 2026-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Troco para'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'PIX'), ('card', 'Cartão'), ('money', 'Dinheiro')], max_length=20, verbose_name='Método de Pagamento'),
        ),
    ]
